<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Customer extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Customer_model');
    } 

    /*
     * Listing of Customer
     */
    function index()
    {
        $data['customer'] = $this->Customer_model->get_all_customer();
        
        $data['_view'] = 'customer/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new Customer
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_user' => $this->input->post('id_user'),
				'alamat' => $this->input->post('alamat'),
				'telepon' => $this->input->post('telepon'),
				'bank' => $this->input->post('bank'),
				'unit_bank' => $this->input->post('unit_bank'),
				'no_rekening' => $this->input->post('no_rekening'),
				'profile' => $this->input->post('profile'),
            );
            
            $customer_id = $this->Customer_model->add_customer($params);
            redirect('customer/index');
        }
        else
        {            
            $data['_view'] = 'customer/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a Customer
     */
    function edit($id_customer)
    {   
        // check if the Customer exists before trying to edit it
        $data['customer'] = $this->Customer_model->get_customer($id_customer);
        
        if(isset($data['customer']['id_customer']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_user' => $this->input->post('id_user'),
					'alamat' => $this->input->post('alamat'),
					'telepon' => $this->input->post('telepon'),
					'bank' => $this->input->post('bank'),
					'unit_bank' => $this->input->post('unit_bank'),
					'no_rekening' => $this->input->post('no_rekening'),
					'profile' => $this->input->post('profile'),
                );

                $this->Customer_model->update_Customer($id_customer,$params);            
                redirect('customer/index');
            }
            else
            {
                $data['_view'] = 'customer/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The Customer you are trying to edit does not exist.');
    } 

    /*
     * Deleting Customer
     */
    function remove($id_customer)
    {
        $customer = $this->Customer_model->get_customer($id_customer);

        // check if the Customer exists before trying to delete it
        if(isset($customer['id_customer']))
        {
            $this->Customer_model->delete_customer($id_customer);
            redirect('customer/index');
        }
        else
            show_error('The Customer you are trying to delete does not exist.');
    }

}
