<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Detail_transaksi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Detail_transaksi_model');
    }

    /*
     * Listing of detail_transaksi
     */
    function index()
    {
        $data['detail_transaksi'] = $this->Detail_transaksi_model->get_all_detail_transaksi();

        $data['_view'] = 'detail_transaksi/index';
        $this->load->view('templates/pure/header');
        $this->load->view('layouts/bulma-dashboard/main', $data);
        $this->load->view('templates/pure/footer');
    }

    /*
     * Adding a new detail_transaksi
     */
    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'no_transaksi' => $this->input->post('no_transaksi'),
                'id_layanan' => $this->input->post('id_layanan'),
            );

            $detail_transaksi_id = $this->Detail_transaksi_model->add_detail_transaksi($params);
            redirect('detail_transaksi/index');
        } else {
            $data['_view'] = 'detail_transaksi/add';
            $this->load->view('templates/pure/header');
            $this->load->view('layouts/bulma-dashboard/main', $data);
            $this->load->view('templates/pure/footer');
        }
    }

    /*
     * Editing a detail_transaksi
     */
    function edit($id_detail)
    {
        // check if the detail_transaksi exists before trying to edit it
        $data['detail_transaksi'] = $this->Detail_transaksi_model->get_detail_transaksi($id_detail);

        if (isset($data['detail_transaksi']['id_detail'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'no_transaksi' => $this->input->post('no_transaksi'),
                    'id_layanan' => $this->input->post('id_layanan'),
                );

                $this->Detail_transaksi_model->update_detail_transaksi($id_detail, $params);
                redirect('detail_transaksi/index');
            } else {
                $data['_view'] = 'detail_transaksi/edit';
                $this->load->view('templates/pure/header');
                $this->load->view('layouts/bulma-dashboard/main', $data);
                $this->load->view('templates/pure/footer');
            }
        } else
            show_error('The detail_transaksi you are trying to edit does not exist.');
    }

    /*
     * Deleting detail_transaksi
     */
    function remove($id_detail)
    {
        $detail_transaksi = $this->Detail_transaksi_model->get_detail_transaksi($id_detail);

        // check if the detail_transaksi exists before trying to delete it
        if (isset($detail_transaksi['id_detail'])) {
            $this->Detail_transaksi_model->delete_detail_transaksi($id_detail);
            redirect('detail_transaksi/index');
        } else
            show_error('The detail_transaksi you are trying to delete does not exist.');
    }
}
