<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class DetailLayanan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        if (!isset($_SESSION)) {
            session_start();
        }
        if (!isset($_SESSION['id_user'])) {
            redirect(base_url());
        }
        $this->load->model('Detail_layanan_model');
        //$this->load->model('Terapi_model');
    }

    /*
     * Listing of Customer
     */
    function index()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['hak_akses']  = $_SESSION['hak_akses'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['email'];

        $data['_view'] = 'layanan/detail';

        $this->load->view('templates/pure/header');
        $this->load->view('layouts/bulma-dashboard/main', $data);
        $this->load->view('templates/pure/footer');
    }

    function listDetailLayanan()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['hak_akses']  = $_SESSION['hak_akses'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['email'];
        $data['detail'] = $this->Detail_layanan_model->get_all_terapis();
        $data['_view'] = 'layanan/list_layanan_admin';

        $this->load->view('templates/pure/header');
        $this->load->view('layouts/bulma-dashboard/main', $data);
        $this->load->view('templates/pure/footer');
    }

    function add()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['hak_akses']  = $_SESSION['hak_akses'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['email'];
        $data['_view']      = 'layanan/detail';

        $this->load->view('templates/pure/header');
        $this->load->view('layouts/bulma-dashboard/main', $data);
        $this->load->view('templates/pure/footer');

        if (isset($_POST) && count($_POST) > 0) {
            $layanan_list   = $this->input->post('layanan');
            $id_terapis     = $this->input->post('id_terapis');
            $this->Detail_layanan_model->delete_detail_layanan($id_terapis);
            //hapus dulu baru tambah
            foreach ($layanan_list as $layanan) {
                $data = array(
                    'id_terapis' => $id_terapis,
                    'id_layanan' => $layanan
                );
                $this->Detail_layanan_model->add_detail_layanan($data);
            }
            redirect('DetailLayanan/index');
        } else {
            $data['_view'] = 'layanan/detail';
            $this->load->view('templates/pure/header');
            $this->load->view('layouts/bulma-dashboard/main', $data);
            $this->load->view('templates/pure/footer');
        }
    }

    function detail_layanan_admin($id_terapis)
    {
        // check if the terapi exists before trying to edit it
        $data['detail']     = $this->Detail_layanan_model->get_terapi($id_terapis);
        $data['nama']       = $_SESSION['nama'];
        $data['hak_akses']  = $_SESSION['hak_akses'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['email'];

        if (isset($data['detail']['id_terapis'])) {

            $data['_view'] = 'layanan/detail_layanan_admin';

            $this->load->view('templates/pure/header');
            $this->load->view('layouts/bulma-dashboard/main', $data);
            $this->load->view('templates/pure/footer');
        } else
        show_error('The terapi you are trying to edit does not exist.');
    }


    function add_admin()
    {


    }

        /*
     * Adding a new Customer
     */
    }
