<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class DetailLayanan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
         if(!isset($_SESSION)){
            session_start();
        }
        if (!isset($_SESSION['id_user'])) {
            redirect(base_url());
        }
        $this->load->model('Detail_layanan_model');
    } 

    /*
     * Listing of Customer
     */
    function index()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['hak_akses']  = $_SESSION['hak_akses'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['email'];
        
        $data['_view'] = 'layanan/detail';
        $this->load->view('layouts/main',$data);
    }

    function add()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['hak_akses']  = $_SESSION['hak_akses'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['email'];
        $data['_view']      = 'layanan/detail';
        $this->load->view('layouts/main',$data);

      if(isset($_POST) && count($_POST) > 0)     
        {   
        $layanan_list = $this->input->post('layanan');
        $id_terapis = $this->input->post('id_terapis');
        $this->Detail_layanan_model->delete_detail_layanan($id_terapis);
        //hapus dulu baru tambah
        foreach($layanan_list as $layanan) {
        $data= array(
            'id_terapis' => $id_terapis,
            'id_layanan' => $layanan
        );
         $this->Detail_layanan_model->add_detail_layanan($data);
        }
        redirect('DetailLayanan/index');
        }
        else
        {            
            $data['_view'] = 'layanan/detail';
            $this->load->view('layouts/main',$data);
        }

    /*
     * Adding a new Customer
     */

}}
