<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Terapi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
         if(!isset($_SESSION)){
            session_start();
        }
        if (!isset($_SESSION['id_user'])) {
            redirect(base_url());
        }
        $this->load->model('Terapi_model');
    } 

    /*
     * Listing of terapis
     */
    function index()
    {
        $data['nama']       = $_SESSION['nama'];
        $data['hak_akses']  = $_SESSION['hak_akses'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['email'];
        $data['terapis'] = $this->Terapi_model->get_all_terapis();
        
        $data['_view'] = 'terapi/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new terapi
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_user' => $this->input->post('id_user'),
				'alamat' => $this->input->post('alamat'),
				'telepon' => $this->input->post('telepon'),
				'bank' => $this->input->post('bank'),
				'unit_bank' => $this->input->post('unit_bank'),
				'no_rekening' => $this->input->post('no_rekening'),
				'ktp' => $this->input->post('ktp'),
				'selfie_ktp' => $this->input->post('selfie_ktp'),
				'profile' => $this->input->post('profile'),
				'status' => $this->input->post('status'),
            );
            
            $terapi_id = $this->Terapi_model->add_terapi($params);
            redirect('terapi/index');
        }
        else
        {            
            $data['_view'] = 'terapi/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a terapi
     */
    function edit($id_terapis)
    {   
        // check if the terapi exists before trying to edit it
        $data['terapi'] = $this->Terapi_model->get_terapi($id_terapis);
        $data['nama']       = $_SESSION['nama'];
        $data['hak_akses']  = $_SESSION['hak_akses'];
        $data['id_user']    = $_SESSION['id_user'];
        $data['email']      = $_SESSION['email'];
        
        if(isset($data['terapi']['id_terapis']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_user' => $this->input->post('id_user'),
					'alamat' => $this->input->post('alamat'),
					'telepon' => $this->input->post('telepon'),
					'bank' => $this->input->post('bank'),
					'unit_bank' => $this->input->post('unit_bank'),
					'no_rekening' => $this->input->post('no_rekening'),
					'ktp' => $this->input->post('ktp'),
					'selfie_ktp' => $this->input->post('selfie_ktp'),
					'profile' => $this->input->post('profile'),
					'status' => $this->input->post('status'),
                );

                $this->Terapi_model->update_terapi($id_terapis,$params);            
                $data['_view'] = 'dashboard';
                $this->load->view('layouts/main',$data);  
            }
            else
            {
                $data['_view'] = 'terapi/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The terapi you are trying to edit does not exist.');
    } 

    /*
     * Deleting terapi
     */
    function remove($id_terapis)
    {
        $terapi = $this->Terapi_model->get_terapi($id_terapis);

        // check if the terapi exists before trying to delete it
        if(isset($terapi['id_terapis']))
        {
            $this->Terapi_model->delete_terapi($id_terapis);
            redirect('terapi/index');
        }
        else
            show_error('The terapi you are trying to delete does not exist.');
    }
    
}
