<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cart_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get customer by id_customer
     */
    function get_cart($id_customer)
    {
        return $this->db->get_where('customer',array('id_customer'=>$id_customer))->row_array();
    }
        
    /*
     * Get all customer
     */
    function get_all_cart()
    {
        // $this->db->order_by('cart', 'desc');
        // return $this->db->get('customer')->result_array();
        $this->db->select('user.nama as terapis,layanan.jenis,layanan.nama,layanan.durasi,layanan.harga,detail_layanan.id_detailLayanan as iddetaillayanan');
        $this->db->from('layanan');
        $this->db->join('detail_layanan', 'layanan.id_layanan=detail_layanan.id_layanan');
        $this->db->join('terapis', 'terapis.id_terapis=detail_layanan.id_terapis');
        $this->db->join('user', 'user.id_user=terapis.id_user');
        return $this->db->get()->result();
    }
        
    /*
     * function to add new customer
     */
    function add_cart($params)
    {
        $this->db->insert('cart',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update customer
     */
    function update_cart($id_customer,$params)
    {
        $this->db->where('id_customer',$id_customer);
        return $this->db->update('customer',$params);
    }
    
    /*
     * function to delete customer
     */
    function delete_cart($id_customer)
    {
        return $this->db->delete('customer',array('id_customer'=>$id_customer));
    }
}
