<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detail_transaksi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detail_transaksi by id_detail
     */
    function get_detail_transaksi($id_detail)
    {
        return $this->db->get_where('detail_transaksi',array('id_detail'=>$id_detail))->row_array();
    }
        
    /*
     * Get all detail_transaksi
     */
    function get_all_detail_transaksi()
    {
        $this->db->order_by('id_detail', 'desc');
        return $this->db->get('detail_transaksi')->result_array();
    }
        
    /*
     * function to add new detail_transaksi
     */
    function add_detail_transaksi($params)
    {
        $this->db->insert('detail_transaksi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update detail_transaksi
     */
    function update_detail_transaksi($id_detail,$params)
    {
        $this->db->where('id_detail',$id_detail);
        return $this->db->update('detail_transaksi',$params);
    }
    
    /*
     * function to delete detail_transaksi
     */
    function delete_detail_transaksi($id_detail)
    {
        return $this->db->delete('detail_transaksi',array('id_detail'=>$id_detail));
    }
}
