<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Layanan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get layanan by id_layanan
     */
    function get_layanan($id_layanan)
    {
        return $this->db->get_where('layanan',array('id_layanan'=>$id_layanan))->row_array();
    }
        
    /*
     * Get all layanan
     */
    function get_all_layanan()
    {
        $this->db->order_by('id_layanan', 'desc');
        return $this->db->get('layanan')->result_array();
    }
        
    /*
     * function to add new layanan
     */
    function add_layanan($params)
    {
        $this->db->insert('layanan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update layanan
     */
    function update_layanan($id_layanan,$params)
    {
        $this->db->where('id_layanan',$id_layanan);
        return $this->db->update('layanan',$params);
    }
    
    /*
     * function to delete layanan
     */
    function delete_layanan($id_layanan)
    {
        return $this->db->delete('layanan',array('id_layanan'=>$id_layanan));
    }
}
