<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Search_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function get_all(){
            $this->db->select('user.nama as terapis,layanan.jenis,layanan.nama,layanan.durasi,layanan.harga,detail_layanan.id_detailLayanan as iddetaillayanan,gambar');
            $this->db->from('layanan');
            $this->db->join('detail_layanan', 'layanan.id_layanan=detail_layanan.id_layanan');
            $this->db->join('terapis', 'terapis.id_terapis=detail_layanan.id_terapis');
            $this->db->join('user', 'user.id_user=terapis.id_user');
        return $this->db->get()->result();
    }
    
   public function get_search_keyword($keyword){
            $this->db->select('user.nama as terapis,layanan.jenis,layanan.nama,layanan.durasi,layanan.harga');
            $this->db->from('layanan');
            $this->db->join('detail_layanan', 'layanan.id_layanan=detail_layanan.id_layanan');
            $this->db->join('terapis', 'terapis.id_terapis=detail_layanan.id_terapis');
            $this->db->join('user', 'user.id_user=terapis.id_user');
            $this->db->like('layanan.nama',$keyword);
            $this->db->or_like('user.nama',$keyword);
        return $this->db->get()->result();
    }
}
// $this->db->query('SELECT user.nama as terapis,layanan.jenis,layanan.nama,layanan.durasi,layanan.harga FROM layanan JOIN detail_layanan ON layanan.id_layanan=detail_layanan.id_layanan JOIN terapis ON terapis.id_terapis=detail_layanan.id_terapis JOIN user ON user.id_user=terapis.id_user WHERE layanan.nama LIKE %{$keyword}% OR user.nama LIKE %{$keyword}%');