<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Terapi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get terapi by id_terapis
     */
    function get_terapi($id_terapis)
    {
        return $this->db->get_where('terapis',array('id_terapis'=>$id_terapis))->row_array();
    }
        
    /*
     * Get all terapis
     */
    function get_all_terapis()
    {
        $this->db->order_by('id_terapis', 'desc');
        return $this->db->get('terapis')->result_array();
    }
        
    /*
     * function to add new terapi
     */
    function add_terapi($params)
    {
        $this->db->insert('terapis',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update terapi
     */
    function update_terapi($id_terapis,$params)
    {
        $this->db->where('id_terapis',$id_terapis);
        return $this->db->update('terapis',$params);
    }
    
    /*
     * function to delete terapi
     */
    function delete_terapi($id_terapis)
    {
        return $this->db->delete('terapis',array('id_terapis'=>$id_terapis));
    }
}
